import Navbar from "@components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col">
        <Navbar />
        <main className="flex-grow w-screen flex justify-center">
          <div className="w-full flex flex-col items-center">{children}</div>
        </main>
      </body>
    </html>
  );
}
