name: Mirror to Personal Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Enterprise Repo
        uses: actions/checkout@v4

      - name: Push to Mirrored Deployed GitHub Repo
        env:
          GITHUB_PAT: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.email "ufgatorai@gmail.com"
          git config --global user.name "Gator-AI"

          # Add mirror repo as a new remote
          git remote add mirror https://Gator-AI:${GITHUB_PAT}@github.com/Gator-AI/vercel-mirror.git
          git push -u mirror main --force
