name: Push to Personal GitHub Repo via SSH

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Enterprise Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to Vercel Mirror Repo
        run: |
          git config --global user.email "ufgatorai@gmail.com"
          git config --global user.name "Gator-AI"

          git remote add mirror git@github.com:Gator-AI/vercel-mirror.git
          git push mirror main --force
